### ISSUE TITLE
Issue: Only fetching the latest post

### ISSUE THREAD

**Issue by mgithens** [huaying/instagram-crawler#77]
`python3 crawler.py posts_full -u cal_foodie -n 3 -o ./output.json`

The above command is only fetching the single most current post.

Any suggestions?

**Comment by bear00712** [comment]
I have the same problem!
I guess the reason is that Instagram change their web interface, so I had the error.
AttributeError: 'NoneType' object has no attribute 'click'

**Comment by LiuTai** [comment]
Same issue here

**Comment by kswgit** [comment]
Thank you for reporting a problem.
This bug is derived from an awkward login modal which is an obstacle to crawl.
So I added a code to sign into them before crawling.
I think this issue is solved, however, please feel free to re-open if it was not.

**Comment by ParhamAbedAzad** [comment]
i still have the same problem
i tried to get posts from different users but it makes no difference
